apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/konflux-ci/build-definitions//pipelines/docker-build/?timeout=120&ref=d42191e766e615e312c7c87af547b238bd495544

patches:
- path: patch.yaml
  target:
    kind: Pipeline
